### PR TITLE
Added Member, Freesider and Alumni Stats

### PR DESCRIPTION
**Pull request by Ki-er**
Added updating stats to voice channels at the request of @CrimsonTome

### CODE REVIEW

**Comment by CrimsonTome** [comment]
Looks good, I will request a review from @lgibson02 as they are more likely than myself to spot any errors as I am unfamiliar with Discord.js. Thank you for your additions

**Review by lgibson02 — CHANGES_REQUESTED** [review]
Please pull latest .eslintrc.json (just updated) and run `npx eslint --fix bot.js` to fix inconsistent styling (I really need to find a way to automate such corrections). I'd also prefer if the update stats procedure was separated on its own rather than being nested in bot `ready`.

Thanks.

**Comment by Ki-er** [comment]
Ran the `npx eslint --fix bot.js` command 
Moved the stats updating to a function. I based it off the other functions and am not familiar with js functions so may have gotten something wrong, happy to fix if I did

**Comment by lgibson02** [comment]
> Ran the `npx eslint --fix bot.js` command Moved the stats updating to a function. I based it off the other functions and am not 

Doesn't seem eslint has worked there. updateVoiceChannelStats is fine, doesn't need to be async though.
I may merge this request and then amend changes myself if you can't get eslint to work.

**Comment by Ki-er** [comment]
Removed the async function 
Ran eslint [here](https://github.com/FreesideHull/FreesideBot/pull/1/commits/a7c0e327b69cf148d470b6d57c505e7548a95097) and it seemed to fix the styling, I ran it again with this current commit and it didnt change anything so probably best to fix the changes manually

**Pull request merged**
